---
#- hosts: ccc2
- name: Show software version
  hosts: row
  connection: paramiko
  gather_facts: no
  
  tasks:
    - name: Get a version string
      raw: "cat /etc/version"
      register: result
      #    - debug: var=result.stdout_lines

    - set_fact:
        result_txt : "{{ result.stdout_lines[0] }}"

    - name: Print strings
      debug:
        msg: "Raw: {{ result.stdout_lines }}; result_txt: {{ result_txt }}"
        verbosity: 1
    - name: Parse the version string
      set_fact:
        opengear_vars:
          "{{ inventory_hostname }}": {model: "{{ result_txt.split(' ')[0] }}", version: "{{ result_txt.split(' ')[2] }}", hash: "{{ result_txt.split(' ')[3] }}"}
    - name: Print debug
      debug:
        msg: "{{ opengear_vars | to_nice_json }}"
